services:
  - type: web
    name: calorie-tracker-backend
    env: python
    plan: free

    buildCommand: |
      pip install poetry &&
      poetry config virtualenvs.create false &&
      poetry install --no-interaction --no-ansi

    startCommand: poetry run uvicorn app.main:app --host 0.0.0.0 --port 10000

    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: DATABASE_URL
        sync: false
      - key: USDA_API_KEY
        sync: false
